export const REGISTER_VOLUNTEER_REQUESTED = "REGISTER_VOLUNTEER_REQUESTED";
export const REGISTER_VOLUNTEER_SUCCEEDED = "REGISTER_VOLUNTEER_SUCCEEDED";
export const REGISTER_VOLUNTEER_FAILED = "REGISTER_VOLUNTEER_FAILED";

export const FETCH_VOLUNTEERS_REQUESTED = "FETCH_VOLUNTEERS_REQUESTED";
export const FETCH_VOLUNTEERS_SUCCEEDED = "FETCH_VOLUNTEERS_SUCCEEDED";
export const FETCH_VOLUNTEERS_FAILED = "FETCH_VOLUNTEERS_FAILED";

export const EDIT_VOLUNTEER_REQUESTED = "EDIT_VOLUNTEER_REQUESTED";
export const EDIT_VOLUNTEER_SUCCEEDED = "EDIT_VOLUNTEER_SUCCEEDED";
export const EDIT_VOLUNTEER_FAILED = "EDIT_VOLUNTEER_FAILED";

export const LOGIN_USER_REQUESTED = "LOGIN_USER_REQUESTED";
export const LOGIN_USER_SUCCEEDED_VOLUNTEER = "LOGIN_USER_SUCCEEDED_VOLUNTEER";
export const LOGIN_USER_SUCCEEDED_ADMIN = "LOGIN_USER_SUCCEEDED_ADMIN";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_HOUSE_LISTING_REQUESTED = "ADD_HOUSE_LISTING_REQUESTED";
export const ADD_HOUSE_LISTING_SUCCEEDED = "ADD_HOUSE_LISTING_SUCCEEDED";
export const ADD_HOUSE_LISTING_FAILED = "ADD_HOUSE_LISTING_FAILED";

export const ADD_PERSON_REQUESTED = "ADD_PERSON_REQUESTED";
export const ADD_PERSON_SUCCEEDED = "ADD_PERSON_SUCCEEDED";
export const ADD_PERSON_FAILED = "ADD_PERSON_FAILED";
